customer/urls.py
from django.urls import path
from customer import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'customer'

urlpatterns = [
    path('addcustomer/', views.AddCutomerView.as_view(), name='addcustomer'),
    path('customerlist/', views.CutomerListView.as_view(), name='customerlist'),
    path('editcustomer/<int:pk>/', views.EditCustomerView.as_view(), name='editcustomer'),
    path('listsupplier/', views.ListsupplierView.as_view(), name='listsupplier'),
    path('addsupplier/', views.AddSupplierView.as_view(), name='addsupplier'),
    path('listmedicine/', views.ListMedicineView.as_view(), name='listmedicine'),
    path('addmedicine/', views.PurchaseMedicineView.as_view(), name='addmedicine'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from dashboard import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'dashboard'

urlpatterns = [
    path('register/', views.RegistrationView.as_view(), name='register'),
    path('', views.LoginView.as_view(), name='login'),
    path('logout/',views.LogoutView.as_view(), name='logout_user'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('invoice/', views.InvoiceView.as_view(), name='invoice'),
    path('createinvoice/', views.CreateInvoiceView.as_view(), name='createinvoice'),
    path('exportinvoce/<str:pk>/', views.ExportInvoiceView.as_view(), name='exportinvoice'),
    path('printinvoice/<str:pk>/', views.PrintInvoice, name='printinvoice'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pharmacy_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('customer/', include('customer.urls'))
]

customer/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin, BaseUserManager
from phonenumber_field.modelfields import PhoneNumberField
from django.db.models.signals import post_save
from django.dispatch import receiver

from django.utils import timezone
import uuid

customer/forms.py
from django import forms
from dashboard.models import Customer, suppiler, Medicine
from django.core.validators import RegexValidator

class AddCustomerForm(forms.ModelForm):

    class Meta:
        model = Customer
        fields = ('name','phone_number', 'dr_name', 'dr_dept', 'dr_hospital')
        
        error_css_class = 'error_msg'
        required_css_class = "required"
        widgets = {
            'name': forms.TextInput(attrs={'class': 'phar-cust-field'}),
            'phone_number': forms.TextInput(attrs={'class': 'phar-cust-field'}),
            'dr_name': forms.TextInput(attrs={'class': 'phar-cust-field'}),
            'dr_dept': forms.TextInput(attrs={'class': 'phar-cust-field'}),
            'dr_hospital': forms.TextInput(attrs={'class': 'phar-cust-field'}),
        }

class AddSupplierForm(forms.ModelForm):
    PAYMENT_CHOICES = (
        ("cash", "Cash"),
        ("upi", "Upi"),
        ("card", "Card"),
    )
    payment_type = forms.ChoiceField(choices=PAYMENT_CHOICES)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['payment_type'].widget.attrs.update({'class': 'phar-cust-field'})

    class Meta:
        model = suppiler
        fields = ('suppiler_name', 'phone_number', 'company_name', 'payment_type')
        
        error_css_class = 'error_msg'
        required_css_class = "required"
        widgets = {
            'suppiler_name': forms.TextInput(attrs={'class': 'phar-cust-field select-supplier', 'id': 'supplier-select'}),
            'phone_number': forms.TextInput(attrs={'class': 'phar-cust-field', 'id': 'phone-number-input'}),
            'company_name': forms.TextInput(attrs={'class': 'phar-cust-field', 'id': 'company-name-input'}),
            'payment_type': forms.Select(attrs={'class': 'phar-cust-field', 'id': 'payment-type-input'}),
        }



class AddMedicineForm(forms.ModelForm):

    class Meta:
        model = Medicine
        fields = ('medicine_name','quantity', 'batch_id', 'exp_date','total_amount')
        exclude = ['suppiler_name', 'price']
        
        error_css_class = 'error_msg'
        required_css_class = "required"
        widgets = {
            'medicine_name': forms.TextInput(attrs={'class': 'phar-cust-field'}),
            'quantity': forms.TextInput(attrs={'class': 'phar-cust-field'}),
            'batch_id': forms.TextInput(attrs={'class': 'phar-cust-field'}),
            'exp_date': forms.TextInput(attrs={'class': 'phar-cust-field','autocomplete': 'off', 'type': 'date'}),
            'total_amount': forms.TextInput(attrs={'class': 'phar-cust-field'}),
        }
    
    def save(self, commit=True):
        instance = super().save(commit=False)
        quantity = instance.quantity
        total_amount = instance.total_amount
        if quantity is not None:
            instance.price = total_amount / quantity  # Assuming price is calculated based on quantity
        if commit:
            instance.save()
        return instance

customer/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
import json
from django.template.loader import render_to_string
from weasyprint import HTML

from customer.forms import AddCustomerForm,AddSupplierForm, AddMedicineForm

from dashboard.models import AiUser, suppiler, Medicine, Customer, Invoice, InvoiceItem

from django.utils import timezone
from dashboard.utils import download_template

@method_decorator(login_required(login_url='/'), name='dispatch')
class AddCutomerView(View):
    
    def get(self, request):
        form = AddCustomerForm()
        return render(request, 'customer/add_customer.html', {'form' : form})

    def post(self, request):
        try:
            form = AddCustomerForm(request.POST)
            if form.is_valid():
                user = form.save()
                return redirect('dashboard:dashboard')
            else:
                return render(request, 'customer/add_customer.html', {'form': form, 'error_message': 'invaild data'})
        except Exception as e:
            print("error--------------", str(e))
            return render(request, 'customer/add_customer.html', {'form': form, 'error_message': str(e)})
        
@method_decorator(login_required(login_url='/'), name='dispatch')
class CutomerListView(View):
    def get(self, request):
        customer_obj = Customer.objects.all().order_by('-date_created')
        return render(request, 'customer/view_customer.html',{'customer_obj':customer_obj})
    
@method_decorator(login_required(login_url='/'), name='dispatch')
class EditCustomerView(View):

    def get(self, request, pk):
        customer = get_object_or_404(Customer, pk=pk)
        form = AddCustomerForm(instance=customer)
        return render(request, 'customer/edit_customer.html',{'form':form})
    def post(self, request, pk):
        customer = get_object_or_404(Customer, pk=pk)
        form = AddCustomerForm(request.POST, instance=customer)
        if form.is_valid():
            form.save()
            return redirect('customer:customerlist')
        else:
            return render(request, 'customer/edit_customer.html', {'form': form, 'error_message': 'invaild data'})

@method_decorator(login_required(login_url='/'), name='dispatch')       
class ListsupplierView(View):
    def get(self, request):
        supplier_obj = suppiler.objects.all().order_by('-date_joined')
        return render(request, 'customer/view_supplier.html',{'supplier_obj':supplier_obj})

@method_decorator(login_required(login_url='/'), name='dispatch')
class ListMedicineView(View):
    def get(self, request):
        med_obj = Medicine.objects.all().order_by('-date_created')
        return render(request, 'customer/view_medicine.html',{'med_obj':med_obj})

@method_decorator(login_required(login_url='/'), name='dispatch')   
class AddSupplierView(View):
    def get(self, request):
        form = AddSupplierForm()
        return render(request, 'customer/add_supplier.html', {'form' : form})
    def post(self, request):
        try:
            form = AddSupplierForm(request.POST)
            if form.is_valid():
                supplier_instance = form.save()
                return redirect('customer:addmedicine')
            else:
                return render(request, 'customer/add_medicine.html', {'form': form, 'error_message': 'invaild data'})
        except Exception as e:
            print("error--------------", str(e))
            return render(request, 'customer/add_medicine.html', {'form': form, 'error_message': str(e)})

@method_decorator(login_required(login_url='/'), name='dispatch')
class PurchaseMedicineView(View):
    def get(self, request):
        form = AddSupplierForm()
        form2 = AddMedicineForm()
        supplier_obj = suppiler.objects.all().order_by('suppiler_name')
        if request.method == 'GET' and request.is_ajax():
            supplier_name = request.GET.get('supplier_name')
            try:
                supplier = suppiler.objects.get(suppiler_name=supplier_name)
                data = {
                    'phone_number': str(supplier.phone_number),
                    'company_name': supplier.company_name,
                    'payment_type': supplier.payment_type,
                }
                return JsonResponse(data)
            except suppiler.DoesNotExist:
                return JsonResponse({'error': 'Supplier not found'}, status=404)
        context ={
            'form' : form,
            'form2' : form2,
            'supplier_obj' : supplier_obj
        }
        return render(request, 'customer/add_medicine.html',context)
    def post(self, request):
        try:
            form = AddSupplierForm(request.POST)
            form2 = AddMedicineForm(request.POST)
            phone_number = form.data.get('phone_number')
            existing_supplier = suppiler.objects.filter(phone_number=phone_number).first()
            if existing_supplier:
                    supplier_instance = existing_supplier
                    print("Supplier with this phone number already exists")
            else:
                print("------------------else part-------------------")
                if form.is_valid():
                    supplier_instance = form.save()
                else:
                    supplier_obj = suppiler.objects.all()
                    return render(request, 'customer/add_medicine.html', {'form': form,'form2':form2,'supplier_obj':supplier_obj, 'error_message': 'invaild data'})
            if form2.is_valid(): 
                medicine_form = form2.save(commit=False)
                batch_id = medicine_form.batch_id 
                print("batch_id", batch_id)
                existing_medicine = Medicine.objects.filter(batch_id=batch_id).first()
                if existing_medicine:
                    # If medicine with same batch_id exists, update it
                    existing_medicine.medicine_name = medicine_form.medicine_name
                    existing_medicine.quantity += medicine_form.quantity
                    existing_medicine.exp_date = medicine_form.exp_date
                    existing_medicine.total_amount = medicine_form.total_amount
                    existing_medicine.price = medicine_form.price
                    existing_medicine.suppiler_name = supplier_instance
                    existing_medicine.date_created = timezone.now()
                    existing_medicine.save()
                else:
                    medicine_form.suppiler_name = supplier_instance
                    medicine_form.save()
                return redirect('customer:listmedicine')
            else:
                supplier_obj = suppiler.objects.all()
                return render(request, 'customer/add_medicine.html', {'form': form,'form2':form2,'supplier_obj':supplier_obj, 'error_message': 'invaild data'})
        except Exception as e:
            print("error--------------", str(e))
            return render(request, 'customer/add_medicine.html', {'form': form, 'form2':form2, 'error_message': str(e)})

templates/customer/view_customer.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Pharmacy</title>
    <link rel="stylesheet" href="{% static 'css/assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/assets/vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'css/assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/assets/css/main.css' %}">
    <link rel="shortcut icon" href="{% static 'css/assets/images/favicon.ico' %}" />
  </head>
  <body>
    <div class="container-scroller">
      <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
        <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
          <a class="navbar-brand brand-logo phar-heading" href="index.html"> Pharmacy</a>
          
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-stretch">
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-menu"></span>
          </button>
          <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item nav-profile dropdown">
              <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                <div class="nav-profile-img">
                  <img src="{% static 'css/assets/images/faces/face1.jpg' %}" alt="image">
                  <span class="availability-status online"></span>
                </div>
                <div class="nav-profile-text">
                  <p class="mb-1 text-black">{{ user }}</p>
                </div>
              </a>
              <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
                <a class="dropdown-item phar-logout-btn" href="{% url 'dashboard:logout_user'%}">
                  <i class="mdi mdi-logout me-2 text-primary"></i> Signout </a>
              </div>
            </li>
          </ul>
          <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
          </button>
        </div>
      </nav>
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_sidebar.html -->
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
          <ul class="nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard:dashboard'%}">
                <span class="menu-title ">Dashboard</span>
                <i class="mdi mdi-home menu-icon"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-bs-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
                <span class="menu-title ">Invoice</span>
                <i class="menu-arrow"></i>
                <i class="mdi mdi-clipboard-text menu-icon "></i>
              </a>
              <div class="collapse" id="ui-basic">
                <ul class="nav flex-column sub-menu">
                  <li class="nav-item"> <a class="nav-link" href="{% url 'dashboard:createinvoice'%}">Create Invoice</a></li>
                  <li class="nav-item"> <a class="nav-link" href="{% url 'dashboard:invoice'%}">Manage invoice</a></li>
                </ul>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-bs-toggle="collapse" href="#ui-basic2" aria-expanded="false" aria-controls="ui-basic">
                <span class="menu-title phar-active">Customers</span>
                <i class="menu-arrow"></i>
                <i class="mdi mdi-account menu-icon phar-active"></i>
              </a>
              <div class="collapse" id="ui-basic2">
                <ul class="nav flex-column sub-menu">
                  <li class="nav-item"> <a class="nav-link" href="{% url 'customer:addcustomer'%}">Create Customer</a></li>
                  <li class="nav-item"> <a class="nav-link" href="{% url 'customer:customerlist'%}">Manage Customer</a></li>
                </ul>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-bs-toggle="collapse" href="#ui-basic3" aria-expanded="false" aria-controls="ui-basic">
                <span class="menu-title">Medicines</span>
                <i class="menu-arrow"></i>
                <i class="mdi mdi-medical-bag menu-icon"></i>
              </a>
              <div class="collapse" id="ui-basic3">
                <ul class="nav flex-column sub-menu">
                  <li class="nav-item"> <a class="nav-link" href="{% url 'customer:addmedicine'%}">Purchase Medicine</a></li>
                  <li class="nav-item"> <a class="nav-link" href="{% url 'customer:listmedicine'%}">Manage Medicine</a></li>
                </ul>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'customer:listsupplier'%}">
                <span class="menu-title">Supplier</span>
                <i class="mdi mdi-store menu-icon"></i>
              </a>
            </li>
          </ul>
        </nav>
        <!-- partial -->
        <div class="main-panel">
          <div class="content-wrapper">
            <div class="page-header">
              <h3 class="page-title">
                <span class="page-title-icon bg-gradient-primary text-white me-2">
                  <i class="mdi mdi-clipboard-text"></i>
                </span> Customer List
              </h3>
            </div>
            
            <div class="row">
              <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                        <div class="phar-inv-head-sec">
                            <div class="phar-inv-head-list">
                                Customer List
                            </div>
                            <div class="row">
                                <div class="col-12 grid-margin">
                                    <div class="table-responsive">
                                        <table class="table">
                                          <thead>
                                            <tr>
                                              <th> Customer Name </th>
                                              <th> Customer Number </th>
                                              <th> Doctor Name </th>
                                              <th> Doctor Department </th>
                                              <th> Doctor Hospital </th>
                                              <th> Date </th>
                                            </tr>
                                          </thead>
                                          <tbody>
                                            {% for i in customer_obj %}
                                            <tr>
                                              <td>
                                                {{ i.name }}
                                              </td>
                                              <td> 
                                                {{ i.phone_number }}
                                              </td>
                                              <td>
                                                {{ i.dr_name }}
                                              </td>
                                              <td>
                                                {{ i.dr_dept }}
                                              </td>
                                              <td>
                                                {{ i.dr_hospital }}
                                              </td>
                                              <td> 
                                                {{ i.date_created }} 
                                              </td>
                                              <td> <a class="phar-inv-view-btn" href="{% url 'customer:editcustomer' i.id %}">View</a> </td>
                                            </tr>
                                            {% endfor %}
                                          </tbody>
                                        </table>
                                      </div>
                                </div>
                            </div>
                        </div>
                  </div>
                </div>
              </div>

            </div>
          </div>
          <!-- content-wrapper ends -->
          <!-- partial:partials/_footer.html -->
          <footer class="footer">
            <div class="container-fluid d-flex justify-content-between">
              <span class="text-muted d-block text-center text-sm-start d-sm-inline-block">Pharmacy Management System</span>
            </div>
          </footer>
          <!-- partial -->
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->


    <script src="{% static 'css/assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="{% static 'css/assets/vendors/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'css/assets/js/jquery.cookie.js' %}" type="text/javascript"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'css/assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'css/assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'css/assets/js/misc.js' %}"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="{% static 'css/assets/js/dashboard.js' %}"></script>
    <script src="{% static 'css/assets/js/todolist.js' %}"></script>

    <!-- End custom js for this page -->
  </body>
</html>